/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panelsPackage;

import database.DbHelper;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import modelsPackage.Item;
import modelsPackage.ItemModel;

/**
 *
 * @author Moust
 */
public class PanelAccountant extends javax.swing.JPanel {

    public PanelAccountant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_icon = new javax.swing.JLabel();
        panelItems = new javax.swing.JPanel();
        sp_items = new javax.swing.JScrollPane();
        String[] headers = new String [] {"ID", "Name", "Brand", "Stock", "Category"};
        ArrayList<Item> rows = new ArrayList<>();
        itemModel = new ItemModel(rows, headers, "Accountant");
        getItems();
        tb_items = new javax.swing.JTable();
        lb_items = new javax.swing.JLabel();
        panelOrders = new javax.swing.JPanel();
        sp_orders = new javax.swing.JScrollPane();
        ls_orders = new javax.swing.JList<>(getOrdersList());
        lb_orders = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 86, 146), 3));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 800));

        lb_icon.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        lb_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Icon.png"))); // NOI18N

        tb_items.setModel(itemModel);
        tb_items.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tb_items.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        sp_items.setViewportView(tb_items);

        lb_items.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_items.setText("Items in stock:");

        javax.swing.GroupLayout panelItemsLayout = new javax.swing.GroupLayout(panelItems);
        panelItems.setLayout(panelItemsLayout);
        panelItemsLayout.setHorizontalGroup(
            panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lb_items, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp_items, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        panelItemsLayout.setVerticalGroup(
            panelItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_items, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sp_items, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ls_orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openOrders(evt);
            }
        });
        sp_orders.setViewportView(ls_orders);

        lb_orders.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lb_orders.setText("Orders not yet recieved:");

        javax.swing.GroupLayout panelOrdersLayout = new javax.swing.GroupLayout(panelOrders);
        panelOrders.setLayout(panelOrdersLayout);
        panelOrdersLayout.setHorizontalGroup(
            panelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdersLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sp_orders)
                    .addGroup(panelOrdersLayout.createSequentialGroup()
                        .addComponent(lb_orders, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelOrdersLayout.setVerticalGroup(
            panelOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_orders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refreshIcon.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(lb_icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openOrders(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openOrders
        JList list = (JList) evt.getSource();
        if (evt.getClickCount() == 2) {
            if (list.getSelectedValue() != null) {
                String[] order = list.getSelectedValue().toString().split(" ");
                int id = Integer.parseInt(order[1]);
                JFrame orderFrame = new JFrame("Order Details");
                orderFrame.setSize(800, 650);
                orderFrame.setLocationRelativeTo(null);
                orderFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                orderFrame.setResizable(false);

                orderFrame.add(new PanelAccountantOrders(id));
                orderFrame.setVisible(true);
            }
        }
    }//GEN-LAST:event_openOrders

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getItems();
        listModel.setSize(0);
        getOrdersList();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_refresh1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb_icon;
    private javax.swing.JLabel lb_items;
    private javax.swing.JLabel lb_orders;
    private javax.swing.JList<String> ls_orders;
    private javax.swing.JPanel panelItems;
    private javax.swing.JPanel panelOrders;
    private javax.swing.JScrollPane sp_items;
    private javax.swing.JScrollPane sp_orders;
    private javax.swing.JTable tb_items;
    // End of variables declaration//GEN-END:variables

    private ItemModel itemModel;
    private DbHelper db = new DbHelper();
    private DefaultListModel<String> listModel = new DefaultListModel<>();;

    private void getItems() {
        itemModel.setRowCount(0);
        ResultSet rs = db.getItems("SELECT * FROM Items");
        try {
            while (rs.next()) {
                Item i = new Item(rs.getInt("itemID"), rs.getString("name"), rs.getString("brand"), rs.getString("category"), rs.getInt("cost"), rs.getInt("price"), rs.getInt("stockCount"), rs.getInt("threshold"), rs.getBoolean("beyondThreshold"));
                itemModel.addRow(i);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private DefaultListModel getOrdersList() {
        ResultSet rs = db.getOrders("SELECT otr.orderID, totalCost, arrivingDate FROM Orders as o,OrderToRecieve as otr WHERE o.orderID = otr.orderID ");
        int previousID = -1;
        try {
            while (rs.next()) {
                if (rs.getInt("orderID") != previousID) {
                    previousID = rs.getInt("orderID");
                    listModel.addElement("ID: " + rs.getInt("orderID") + " Cost: " + rs.getInt("totalCost") + " ArrivingDate: " + rs.getString("arrivingDate"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelAccountant.class.getName()).log(Level.SEVERE, null, ex);
        }

        return listModel;
    }

}
